### PR TITLE
Add gating.yml

### PR DESCRIPTION
**Pull request by dbenoit17**
This commit adds PR checks for ubi7, ubi8, ubi9, c8s, and c9s.

### CODE REVIEW

**Comment by dbenoit17** [comment]
This won't pass on el7/el8 until #75 is merged.

**Comment by dbenoit17** [comment]
Here's an example PR in my go+fips fork where the jobs get triggered automatically in the `check` tab.
https://github.com/dbenoit17/go-fips/pull/1/checks

**Review by alexsaezm — APPROVED** [review]
LGTM

**Review by derekparker — APPROVED** [review]
LGTM

**Pull request merged**
