### PR TITLE
Update to Go 1.20.3

### PR DESCRIPTION
**Pull request by dbenoit17**

### CODE REVIEW

**Review by derekparker — APPROVED** [review]
LGTM

**Review by derekparker — APPROVED** [review]
1.20.3 change LGTM

**Comment by dbenoit17** [comment]
@derekparker just pushed an update fixing go.mod.  The original commits generated the patch using `go mod tidy -go=1.16`, and while I had reset the script to use `go mod tidy` without the flag before pushing, the Go base version in the patch was still set to Go 1.16.  The latest commit fixes that.

**Comment by derekparker** [comment]
@dbenoit17 ack, +1, thanks for fixing that!

**Pull request merged**
