### PR TITLE
Go 1.18.8

### PR DESCRIPTION
**Pull request by jjlin**
Merge the Go 1.18.8 commits from the upstream [dev.boringcrypto.go1.18](https://github.com/golang/go/commits/dev.boringcrypto.go1.18) branch, currently at [94108e2](https://github.com/golang/go/commit/94108e21ab6ff1e182fe4fe8cac12f5d0272a019).

### CODE REVIEW

**Comment by jjlin** [comment]
It would be helpful if you could also add a tag for people who need that, thanks.

**Review by dbenoit17 — APPROVED** [review]
LGTM

**Review by derekparker — APPROVED** [review]
LGTM

**Comment by derekparker** [comment]
Merged and tagged, thanks!

**Pull request merged**
